# Generated by Django 4.0.4 on 2022-05-16 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('register_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('register_date', models.DateTimeField(default=datetime.datetime.now)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.operation')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('register_date', models.DateTimeField(default=datetime.datetime.now)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.operation')),
            ],
        ),
    ]
